#!/bin/bash

#Скрипт для автоматизации сбора данных о показаниях приборов учёта расхода воды.
#Расчитан на работу с планировщиком crontab

#Объявляем переменные окружения
DISPLAY=:0.0
#SESSION_MANAGER=local/reu-sigma:@/tmp/.ICE-unix/897,unix/reu-sigma:/tmp/.ICE-unix/897
XAUTHORITY=/home/reu/.Xauthority
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
BEEP=/usr/share/sounds/freedesktop/stereo/bell.oga
#Экспортируем окружения
export DISPLAY SESSION_MANAGER XAUTHORITY DBUS_SESSION_BUS_ADDRES XDG_RUNTIME_DIR BEEP


#объявляем переменной рабочий файл
schet=schetch
this=waterdata
#schet=/mnt/E/РЭУ/Счётчик.ods

#готовим сегодняшнюю дату
datex=`date +'%d.%m.%Y'`
today=$datex

#удаляем пустые строки файла
`sed -i '/^$/d' $schet`

#читаем последнюю строку из документа в формате "вчера, показания, расход"
yest=`tail -1 $schet`
IFS=","
read -a strarr <<< "$yest"
y_day=${strarr[0]}       #вчерашняя дата
last_val=${strarr[1]}    #показания
sum=${strarr[2]}         #расход

#защита от залипания клавиш и других косяков
if [ $last_val -ge 100000 ]
then
	kdialog --title "Ошибка РВК" --error "Неожиданные предыдущие показания"
	exec mousepad $schet
fi


#создаем форму ввода показаний счетчика
inpval=`kdialog --title "РВК Воронеж - СИГМА" --inputbox "Введите сегодняшние показания счётчика расхода воды. Предыдущие показания: $last_val" "$last_val"`
if [[ $? = 0 ]] #при наличии введенного значения
then
	val=$inpval

	#считаем текущий расход
	let "take = $val - $last_val"
	#echo "$y_day, $last_val, $sum"
	#проверяем актуальность данных и вносим их в учёт
	if [[ $take -le 0 ]] 
	then
		kdialog --title "Что-то пошло не так" --error "Текущие показания меньше или равны предыдущим"
		`. $this` # РЕКУРСИВНЫЙ ПЕРЕЗАПУСК !!!
		exit
	elif [[ $take -ge 1000 ]]
	then
		kdialog --title "Что-то пошло не так" --error "Не могли вы израсходовать столько воды. Перепроверьте"
        	exec mousepad $schet
	else
		echo "$today,$val,$take" >> $schet
	fi
else #при отмене ввода
	kdialog --title "Что-то пошло не так" --error "Не хотите через форму - вводите вручную."
        exec mousepad $schet
fi

#немножко поумничаем
if [[ $take -gt 20 ]]
then
	alias beep='paplay $BEEP --volume100'
	note="Внимание! Расход превысил $take! Вероятность аварии."
	beep
elif [[ $take -lt 6 ]]
then
	note="Очень экономный расход."
else
	note="Расход воды в пределах нормы."
fi
kdialog --title "Данные приняты!" --msgbox "$note" 

#Приглашаем посмотреть сформированный файл
kdialog --title "Учёт показаний" --warningcontinuecancel "Вы можете ознакомиться с журналом учёта показаний расхода воды"
	if [ $? = 0 ]
	then
		exec mousepad $schet
	else
		exit
	fi
exit
